### ISSUE TITLE
[Bug] For information only: AppData use of @lru_cache decorator causes Error with Python3.7

### ISSUE THREAD

**Issue by jeromemassot** [IBM/zshot#12]
# Summary

AppData module uses @lru_cache decorator without ( ) which apparently is not compatible with Python < 3.8 and this causes an Error when importing config.py which uses AppData.

**To Reproduce**
import zhot

**Expected behavior**
It should be imported without error.

**Fix**
It may be interesting to precise that Python version >= 3.8 is needed until AppData fixes the problem.

**Remark**
I am not a CS so my analysis of this problem could be totally wrong. If so, I would be thankful for anyone giving me a by-pass when working with Python 3.7

Thanks

Best regards

Jerome

**Comment by GabrielePicco** [comment]
Thanks @jeromemassot for noticing, the bug should be resolved in #5. We got rid of AppData lib and just rely on pathlib. Will verify on python 3.6 and 3.7 before closing this issue.

**Comment by jeromemassot** [comment]
Thanks @GabrielePicco Gabriele for the comment.

**Comment by GabrielePicco** [comment]
Problem was solved with #5 and merged in master, it will be included in the next release. Thanks again for reporting the issue.
