### ISSUE TITLE
[Bug] Error on using LinkerBlink in Google Colab

### ISSUE THREAD

**Issue by vvkishere** [IBM/zshot#22]
# Summary

**Describe the bug**
I tried using LinkerBlink as the linker on Google colab. I also installed the blink module using the pip command. I restarted the instance and tried again but I am getting the same error

Exception                                 Traceback (most recent call last)
[<ipython-input-12-b4900ceecf4f>](https://localhost:8080/#) in <module>
      1 extractor = MentionsExtractorSpacy(ExtractorType.POS)
----> 2 linker = LinkerBlink()

[/usr/local/lib/python3.7/dist-packages/zshot/linker/linker_blink.py](https://localhost:8080/#) in __init__(self, index)
     65 
     66         if not pkgutil.find_loader("blink"):
---> 67             raise Exception("Blink module not installed. You need to install blink in order to use the Blink Linker."
     68                             "Install it with: pip install -e git+https://github.com/facebookresearch/BLINK.git#egg"
     69                             "=BLINK")

Exception: Blink module not installed. You need to install blink in order to use the Blink Linker.Install it with: pip install -e git+https://github.com/facebookresearch/BLINK.git#egg=BLINK

This error does not come up when you use LinkerTARS

**To Reproduce**
1. pip install zshot, spacy[transformers], Blink (!pip install -e git+https://github.com/facebookresearch/BLINK.git#egg=BLINK)
2. Restart the instance
3. Set up the code as per instructions in the usage manual and use linker = LinkerBlink(). The mention extractor is ExtractorType.POS
**Expected behavior**
A clear and concise description of what you expected to happen. linker is supposed to load the Blink linker .

**Comment by GabrielePicco** [comment]
Hi @vvkishere ,
BLINK requires around 20GB of spaces to download the Wikipedia entities embeddings, unfortunately on Colab it will fail. We are generating the wikipedia prefix trie and adding Wikification support for the REGEN linker (our reimplementation of [GENRE](https://github.com/facebookresearch/GENRE)), this Wikifaction method is less resource intensive and will work in Colab.
I'm closing the issue, but I will add a comment here when the new approach is available.

**Comment by vvkishere** [comment]
Thank you for your response.

**Comment by GabrielePicco** [comment]
@vvkishere we recently added out-of-the-box Wikification trough Regen approach, here you can find an example: https://github.com/IBM/zshot/pull/44.

It requires lower resources/computation with comparable performance.
