### ISSUE TITLE
[Bug] TypeError when printing DatasetWithEntities

### ISSUE THREAD

**Issue by marmg** [IBM/zshot#3]
# Summary
`TypeError` raises when printing a `DatasetWithEntities`.

**Describe the bug**
When printing, displaying or representing a `DatasetWithEntities` next error raises:
```python
TypeError: 'Entity' object is not subscriptable
```

**To Reproduce**
```python
from zshot.evaluation.dataset import load_ontonotes

dataset = load_ontonotes()
print(dataset)
```

**Expected behavior**
The result should print a summary of the `DatasetDict` with the splits, columns and number of rows per split.

**Comment by r121196** [comment]
Type error raised when importing evaluate 

`TypeError: 'type' object is not subscriptable`

obtained while 

`from zshot.evaluation.zshot_evaluate import evaluate `

**Comment by marmg** [comment]
Hi! Thank you for your comment.

Unfortunately, I'm unable to reproduce the error, when I do `import zshot.evaluation` it works without any problem. Could you please provide information about the version of Zshot you are using?

**Comment by marmg** [comment]
Related [StackOverflow post](https://stackoverflow.com/questions/26920955/typeerror-type-object-is-not-subscriptable-when-indexing-in-to-a-dictionary)

It seems next typing fails with Python < 3.9:
`def load_medmentions() -> DatasetDict[DatasetWithEntities]:`

This is due to the class `DatasetDict` of `datasets` extending `dict`. `dict` is a type, and it's not subscriptable in Python<3.9 (for typing it's used `Dict`, not `dict`)
