### ISSUE TITLE
Improve relationship recognition documentation & tutorial

### ISSUE THREAD

**Issue by qinglongheu** [IBM/zshot#40]
Hi, thanks for your amazing work, I am doing research about relationships recognition, can you add a tutorial notebook for providing relationship recognition? I would very appreciate it!

**Comment by GabrielePicco** [comment]
Hi @qinglongheu , thanks for the comment. We are working on improving the documentation.
In the meanwhile here there is a simple example notebook: https://colab.research.google.com/drive/1YiZva8SMBR1K66j2QdSvJoPhjRyntBLQ?usp=sharing

**Comment by GabrielePicco** [comment]
Closing as a notebook has been added to the Readme/Doc
