### ISSUE TITLE
Add support for torch 2.0

### ISSUE THREAD

**Issue by ab3llini** [IBM/zshot#70]
# Scenario summary
Apple Silicon users cannot run zshot due to torch version being pinned to be strictly less than 2.0 (`"torch>=1,<2"`)

# Proposed solution
Update torch to 2.0 and release a new wheel on PyPI 🚀

**Comment by ab3llini** [comment]
It shouln't really be that hard, I could open a PR if I find some time.

Tips on this => https://towardsdatascience.com/tips-and-tricks-for-upgrading-to-pytorch-2-3127db1d1f3d

**Comment by marmg** [comment]
Thank you @ab3llini. I have removed the version constraint, as it should already work with `torch==2.0`. I will merge the PR as soon as possible.

Regarding a new release, we plan to release a new version soon, but we want to finish some things first. I will ping you when ready. Until then, you can install it from the git master branch:
`pip install git+https://github.com/IBM/zshot.git@main`
