### ISSUE TITLE
[Bug] ZShot Displacy doesn't return the markup

### ISSUE THREAD

**Issue by marmg** [IBM/zshot#9]
# Summary
The displacy.render method should return the rendered HTML markup, but currently isn't returning anything

**Describe the bug**
The displacy.render method should return the rendered HTML markup when is not in Jupyter Notebook, but currently isn't returning anything. 

**To Reproduce**
```python
from zshot.utils.data_models import Entity
from zshot.linker import LinkerSMXM
from zshot import PipelineConfig
from zshot.utils.displacy import displacy

nlp = spacy.blank('en')
config = PipelineConfig(
    entities=[
        Entity(name="company", description="The name of a company"),
        Entity(name="location", description="A physical location"),
        Entity(name="chemical compound", description="any substance composed of identical molecules consisting of atoms of two or more chemical elements."),
        Entity(name="organic compound", description="Any of a large class of chemical compounds in which one or more atoms of carbon are covalently linked to atoms of other elements, most commonly hydrogen, oxygen, or nitrogen. The few carbon-containing compounds not classified as organic include carbides, carbonates, and cyanides. See chemical compound.")
    ], 
    linker=LinkerSMXM()
)
nlp.add_pipe("zshot", config=config, last=True)

text_acetamide = "CH2O2 is a chemical compound similar to Acetamide used in International Business " \
        "Machines Corporation (IBM) to create new materials that act like PAGs."

doc = nlp(text_acetamide)
res = displacy.render(doc, style="ent", jupyter=False)
print(res is None)
```
```
True
```

**Expected behavior**
It should return the HTML Markup of the visualization.

```python
from spacy import displacy

nlp = spacy.blank('en')
config = PipelineConfig(
    entities=[
        Entity(name="company", description="The name of a company"),
        Entity(name="location", description="A physical location"),
        Entity(name="chemical compound", description="any substance composed of identical molecules consisting of atoms of two or more chemical elements."),
        Entity(name="organic compound", description="Any of a large class of chemical compounds in which one or more atoms of carbon are covalently linked to atoms of other elements, most commonly hydrogen, oxygen, or nitrogen. The few carbon-containing compounds not classified as organic include carbides, carbonates, and cyanides. See chemical compound.")
    ], 
    linker=LinkerSMXM()
)
nlp.add_pipe("zshot", config=config, last=True)

text_acetamide = "CH2O2 is a chemical compound similar to Acetamide used in International Business " \
        "Machines Corporation (IBM) to create new materials that act like PAGs."

doc = nlp(text_acetamide)
res = displacy.render(doc, style="ent", jupyter=False)
print(res is None)
```
```
False
```

**Comment by AkashKhamkar** [comment]
Hey @marmg change the code from `res = displacy.render(doc, style="ent", jupyter=False)` to `res = displacy.serve(doc, style="ent")` and it will work and show the renders in the browser tab.  I would suggest only use displacy.render() when using in a jupyter notebook .

Below is the ouput image of the render.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/34622497/193813845-cdb5764e-231a-4e11-ab2d-dd60cb108e13.png">

**Comment by GabrielePicco** [comment]
Thanks for the comment @AkashKhamkar , this bug should be fixed in #10

**Comment by AkashKhamkar** [comment]
you changed and pushed it already, that some fast bug fixing!  :)

**Comment by marmg** [comment]
Hello @AkashKhamkar. Thank you for your answer.

The `displacy.serve` function will indeed show the result in the browser, but it doesn't return anything. If the user wants to save the HTML of the visualization, the `displacy.render` function shall be used, and it should return the HTML like the original `displacy`.

**Comment by GabrielePicco** [comment]
@AkashKhamkar indeed, all the arguments are passed to the original Spacy method, the only function of our wrapper is to automatically add colors to user defined entities.

**Comment by GabrielePicco** [comment]
@AkashKhamkar indeed, all the arguments are passed to the original Spacy method, the only function of our wrapper is to automatically add colors to user defined entities.
